# jobfirm平台 内部调用密钥
jobfirm:
  internal-secret: "jobfirm-2026"

jwt:
  secret: "jobfirmplatformsecretkeyjobfirmplatformsecretkey"
  expire: 86400
  token-cache-prefix: "auth:token:"

server:
  port: 8081
  error:
    include-message: always
    include-stacktrace: always

spring:
  application:
    name: auth-service

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
    loadbalancer:
      enabled: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.jobfirm: DEBUG
