jobfirm:
  internal-secret: "jobfirm-2026"
server:
  port: 8081
  error:
    include-message: always
    include-stacktrace: always
spring:
  application:
    name: jobfirm-core
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  datasource:
    dynamic:
      primary: job_firm_core
      strict: false
      datasource:
        job_firm_core:
          url: jdbc:mysql://localhost:3306/job_firm_core?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
          username: root
          password: root123
          driver-class-name: com.mysql.cj.jdbc.Driver
feign:
  client:
    auth:
      url: http://localhost:8081
    user:
      url: http://localhost:8081
    firm:
      url: http://localhost:8083
    job:
      url: http://localhost:8083
    order:
      url: http://localhost:8085
    payment:
      url: http://localhost:8086
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
logging:
  level:
    com.jobfirm: DEBUG
